class ItemsListEvidenceGetStaff {
  int STAFF_ID;
  int STAFF_TYPE;
  String STAFF_CODE;
  int STAFF_REF_ID;
  String ID_CARD;
  int TITLE_ID;
  String TITLE_NAME_TH;
  String TITLE_SHORT_NAME_TH;
  String FIRST_NAME;
  String LAST_NAME;
  String OPREATION_POS_NAME;
  String OPREATION_POS_LAVEL_NAME;
  String OPERATION_OFFICE_CODE;
  String OPERATION_OFFICE_NAME;
  String OPERATION_OFFICE_SHORT_NAME;
  //added 20-09-2019
  String BIRTH_DATE;
  String OPERATION_POS_CODE;
  String OPREATION_POS_LEVEL;
  String OPERATION_POS_LEVEL_NAME;
  String OPERATION_DEPT_CODE;
  String OPERATION_DEPT_NAME;
  int OPERATION_DEPT_LEVEL;
  String OPERATION_UNDER_DEPT_CODE;
  String OPERATION_UNDER_DEPT_NAME;
  int OPERATION_UNDER_DEPT_LEVEL;
  String OPERATION_WORK_DEPT_CODE;
  String OPERATION_WORK_DEPT_NAME;
  int OPERATION_WORK_DEPT_LEVEL;

  int CONTRIBUTOR_ID;
  bool IsCheck;

  ItemsListEvidenceGetStaff({
    this.STAFF_ID,
    this.STAFF_TYPE,
    this.STAFF_CODE,
    this.STAFF_REF_ID,
    this.ID_CARD,
    this.TITLE_ID,
    this.TITLE_NAME_TH,
    this.TITLE_SHORT_NAME_TH,
    this.FIRST_NAME,
    this.LAST_NAME,
    this.OPREATION_POS_NAME,
    this.OPREATION_POS_LAVEL_NAME,
    this.OPERATION_OFFICE_CODE,
    this.OPERATION_OFFICE_NAME,
    this.OPERATION_OFFICE_SHORT_NAME,
    this.BIRTH_DATE,
    this.OPERATION_POS_CODE,
    this.OPREATION_POS_LEVEL,
    this.OPERATION_POS_LEVEL_NAME,
    this.OPERATION_DEPT_CODE,
    this.OPERATION_DEPT_NAME,
    this.OPERATION_DEPT_LEVEL,
    this.OPERATION_UNDER_DEPT_CODE,
    this.OPERATION_UNDER_DEPT_NAME,
    this.OPERATION_UNDER_DEPT_LEVEL,
    this.OPERATION_WORK_DEPT_CODE,
    this.OPERATION_WORK_DEPT_NAME,
    this.OPERATION_WORK_DEPT_LEVEL,
    this.CONTRIBUTOR_ID,
    this.IsCheck,
  });
}