class ItemsOAGMasStaff {
  int STAFF_ID;
  int TITLE_ID;
  String STAFF_CODE;
  String ID_CARD;
  int STAFF_TYPE;
  String TITLE_NAME_TH;
  String TITLE_NAME_EN;
  String TITLE_SHORT_NAME_TH;
  String TITLE_SHORT_NAME_EN;
  String FIRST_NAME;
  String LAST_NAME;
  String BIRTH_DATE;
  String OPERATION_POS_CODE;
  String OPREATION_POS_NAME;
  String OPREATION_POS_LEVEL;
  String OPREATION_POS_LAVEL_NAME;
  String OPERATION_DEPT_CODE;
  String OPERATION_DEPT_NAME;
  int OPERATION_DEPT_LEVEL;
  String OPERATION_UNDER_DEPT_CODE;
  String OPERATION_UNDER_DEPT_NAME;
  int OPERATION_UNDER_DEPT_LEVEL;
  String OPERATION_WORK_DEPT_CODE;
  String OPERATION_WORK_DEPT_NAME;
  int OPERATION_WORK_DEPT_LEVEL;
  String OPERATION_OFFICE_CODE;
  String OPERATION_OFFICE_NAME;
  String OPERATION_OFFICE_SHORT_NAME;
  String MANAGEMENT_POS_NAME;
  int STATUS;
  int IS_ACTIVE;

  int CONTRIBUTOR_ID;
  String ArrestType;
  List<String> ArrestTypeItems;
  bool IsCreated;

  ItemsOAGMasStaff({
    this.STAFF_ID,
    this.TITLE_ID,
    this.STAFF_CODE,
    this.ID_CARD,
    this.STAFF_TYPE,
    this.TITLE_NAME_TH,
    this.TITLE_NAME_EN,
    this.TITLE_SHORT_NAME_TH,
    this.TITLE_SHORT_NAME_EN,
    this.FIRST_NAME,
    this.LAST_NAME,
    this.BIRTH_DATE,
    this.OPERATION_POS_CODE,
    this.OPREATION_POS_NAME,
    this.OPREATION_POS_LEVEL,
    this.OPREATION_POS_LAVEL_NAME,
    this.OPERATION_DEPT_CODE,
    this.OPERATION_DEPT_NAME,
    this.OPERATION_DEPT_LEVEL,
    this.OPERATION_UNDER_DEPT_CODE,
    this.OPERATION_UNDER_DEPT_NAME,
    this.OPERATION_UNDER_DEPT_LEVEL,
    this.OPERATION_WORK_DEPT_CODE,
    this.OPERATION_WORK_DEPT_NAME,
    this.OPERATION_WORK_DEPT_LEVEL,
    this.OPERATION_OFFICE_CODE,
    this.OPERATION_OFFICE_NAME,
    this.OPERATION_OFFICE_SHORT_NAME,
    this.MANAGEMENT_POS_NAME,
    this.STATUS,
    this.IS_ACTIVE,
    this.CONTRIBUTOR_ID,
    this.ArrestType,
    this.ArrestTypeItems,
    this.IsCreated,
  });

  factory ItemsOAGMasStaff.fromJson(Map<String, dynamic> json) {
    return ItemsOAGMasStaff(
      STAFF_ID: json['STAFF_ID'],
      TITLE_ID: json['TITLE_ID'],
      STAFF_CODE: json['STAFF_CODE'],
      ID_CARD: json['ID_CARD'],
      STAFF_TYPE: json['STAFF_TYPE'],
      TITLE_NAME_TH: json['TITLE_NAME_TH'],
      TITLE_NAME_EN: json['TITLE_NAME_EN'],
      TITLE_SHORT_NAME_TH: json['TITLE_SHORT_NAME_TH'],
      TITLE_SHORT_NAME_EN: json['TITLE_SHORT_NAME_EN'],
      FIRST_NAME: json['FIRST_NAME'],
      LAST_NAME: json['LAST_NAME'],
      BIRTH_DATE: json['BIRTH_DATE'],
      OPERATION_POS_CODE: json['OPERATION_POS_CODE'],
      OPREATION_POS_NAME: json['OPREATION_POS_NAME'],
      OPREATION_POS_LEVEL: json['OPREATION_POS_LEVEL'],
      OPREATION_POS_LAVEL_NAME: json['OPERATION_POS_LEVEL_NAME'],
      OPERATION_DEPT_CODE: json['OPERATION_DEPT_CODE'],
      OPERATION_DEPT_NAME: json['OPERATION_DEPT_NAME'],
      OPERATION_DEPT_LEVEL: json['OPERATION_DEPT_LEVEL'],
      OPERATION_UNDER_DEPT_CODE: json['OPERATION_UNDER_DEPT_CODE'],
      OPERATION_UNDER_DEPT_NAME: json['OPERATION_UNDER_DEPT_NAME'],
      OPERATION_UNDER_DEPT_LEVEL: json['OPERATION_UNDER_DEPT_LEVEL'],
      OPERATION_WORK_DEPT_CODE: json['OPERATION_WORK_DEPT_CODE'],
      OPERATION_WORK_DEPT_NAME: json['OPERATION_WORK_DEPT_NAME'],
      OPERATION_WORK_DEPT_LEVEL: json['OPERATION_WORK_DEPT_LEVEL'],
      OPERATION_OFFICE_CODE: json['OPERATION_OFFICE_CODE'],
      OPERATION_OFFICE_NAME: json['OPERATION_OFFICE_NAME'],
      OPERATION_OFFICE_SHORT_NAME: json['OPERATION_OFFICE_SHORT_NAME'],
      MANAGEMENT_POS_NAME: json['MANAGEMENT_POS_NAME'],
      STATUS: json['STATUS'],
      IS_ACTIVE: json['IS_ACTIVE'],
      CONTRIBUTOR_ID: 14,
      ArrestType: "ผู้จับกุม",
      ArrestTypeItems: ["ผู้จับกุม", "ผู้ร่วมจับกุม", "ผู้สั่งการ"],
      IsCreated: false,
    );
  }
}
