
class ItemsCompareListIndicmentProduct {
  int PRODUCT_INDICTMENT_ID;
  int PRODUCT_ID;
  int INDICTMENT_ID;
  double SIZES;
  String SIZES_UNIT;
  double QUANTITY;
  String QUANTITY_UNIT;
  double VOLUMN;
  String VOLUMN_UNIT;
  String PRODUCT_GROUP_NAME;
  String PRODUCT_CATEGORY_NAME;
  String PRODUCT_TYPE_NAME;
  String PRODUCT_SUBTYPE_NAME;
  String PRODUCT_SUBSETTYPE_NAME;
  String PRODUCT_BRAND_NAME_TH;
  String PRODUCT_BRAND_NAME_EN;
  String PRODUCT_SUBBRAND_NAME_TH;
  String PRODUCT_SUBBRAND_NAME_EN;
  String PRODUCT_MODEL_NAME_TH;
  String PRODUCT_MODEL_NAME_EN;
  String PRODUCT_CODE;
  String PRODUCT_GROUP_ID;
  String PRODUCT_GROUP_CODE;
  String PRODUCT_CATEGORY_ID;
  String PRODUCT_CATEGORY_CODE;

  ItemsCompareListIndicmentProduct({
    this.PRODUCT_ID,
    this.PRODUCT_INDICTMENT_ID,
    this.PRODUCT_GROUP_NAME,
    this.PRODUCT_CATEGORY_NAME,
    this.PRODUCT_TYPE_NAME,
    this.PRODUCT_SUBTYPE_NAME,
    this.PRODUCT_BRAND_NAME_TH,
    this.PRODUCT_BRAND_NAME_EN,
    this.PRODUCT_SUBBRAND_NAME_TH,
    this.PRODUCT_SUBBRAND_NAME_EN,
    this.PRODUCT_MODEL_NAME_TH,
    this.PRODUCT_MODEL_NAME_EN,
    this.SIZES,
    this.QUANTITY,
    this.VOLUMN,
    this.SIZES_UNIT,
    this.QUANTITY_UNIT,
    this.VOLUMN_UNIT,
    this.PRODUCT_CODE,
  this.PRODUCT_GROUP_ID,
  this.PRODUCT_GROUP_CODE,
  this.PRODUCT_CATEGORY_ID,
  this.PRODUCT_CATEGORY_CODE,
  });

  factory ItemsCompareListIndicmentProduct.fromJson(Map<String, dynamic> js) {
    return ItemsCompareListIndicmentProduct(
      PRODUCT_ID: js['PRODUCT_ID'],
      PRODUCT_INDICTMENT_ID: js['PRODUCT_INDICTMENT_ID'],
      PRODUCT_CATEGORY_NAME: js['PRODUCT_CATEGORY_NAME'],
      PRODUCT_GROUP_NAME: js['PRODUCT_GROUP_NAME'],
      PRODUCT_TYPE_NAME: js['PRODUCT_TYPE_NAME'],
      PRODUCT_SUBTYPE_NAME: js['PRODUCT_SUBTYPE_NAME'],
      PRODUCT_BRAND_NAME_TH: js['PRODUCT_BRAND_NAME_TH'],
      PRODUCT_BRAND_NAME_EN: js['PRODUCT_BRAND_NAME_EN'],
      PRODUCT_SUBBRAND_NAME_TH: js['PRODUCT_SUBBRAND_NAME_TH'],
      PRODUCT_SUBBRAND_NAME_EN: js['PRODUCT_SUBBRAND_NAME_EN'],
      PRODUCT_MODEL_NAME_TH: js['PRODUCT_MODEL_NAME_TH'],
      PRODUCT_MODEL_NAME_EN: js['PRODUCT_MODEL_NAME_EN'],
      SIZES: js['SIZES'],
      QUANTITY: js['QUANTITY'],
      VOLUMN: js['VOLUMN'],
      SIZES_UNIT: js['SIZES_UNIT'],
      QUANTITY_UNIT: js['QUANTITY_UNIT'],
      VOLUMN_UNIT: js['VOLUMN_UNIT'],

      PRODUCT_CODE: js['PRODUCT_CODE'],
      PRODUCT_GROUP_ID: js['PRODUCT_GROUP_ID'],
      PRODUCT_GROUP_CODE: js['PRODUCT_GROUP_CODE'],
      PRODUCT_CATEGORY_ID: js['PRODUCT_CATEGORY_ID'],
    );
  }
}