
class ItemsProveStaff {
  final int STAFF_ID;
  final int PROVE_ID;
  final int STAFF_REF_ID;
  final int TITLE_ID;
  final String STAFF_CODE;
  final String ID_CARD;
  final int STAFF_TYPE;
  final String TITLE_NAME_TH;
  final String TITLE_NAME_EN;
  final String TITLE_SHORT_NAME_TH;
  final String TITLE_SHORT_NAME_EN;
  final String FIRST_NAME;
  final String LAST_NAME;
  final int AGE;
  final String OPERATION_POS_CODE;
  final String OPREATION_POS_NAME;
  final String OPREATION_POS_LEVEL;
  final String OPERATION_POS_LEVEL_NAME;
  final String OPERATION_DEPT_CODE;
  final String OPERATION_DEPT_NAME;
  final int OPERATION_DEPT_LEVEL;
  final String OPERATION_UNDER_DEPT_CODE;
  final String OPERATION_UNDER_DEPT_NAME;
  final int OPERATION_UNDER_DEPT_LEVEL;
  final String OPERATION_WORK_DEPT_CODE;
  final String OPERATION_WORK_DEPT_NAME;
  final int OPERATION_WORK_DEPT_LEVEL;
  final String OPERATION_OFFICE_CODE;
  final String OPERATION_OFFICE_NAME;
  final String OPERATION_OFFICE_SHORT_NAME;
  final String MANAGEMENT_POS_CODE;
  final String MANAGEMENT_POS_NAME;
  final int MANAGEMENT_POS_LEVEL;
  final String MANAGEMENT_POS_LEVEL_NAME;
  final String MANAGEMENT_DEPT_CODE;
  final String MANAGEMENT_DEPT_NAME;
  final int MANAGEMENT_DEPT_LEVEL;
  final String MANAGEMENT_UNDER_DEPT_CODE;
  final String MANAGEMENT_UNDER_DEPT_NAME;
  final int MANAGEMENT_UNDER_DEPT_LEVEL;
  final String MANAGEMENT_WORK_DEPT_CODE;
  final String MANAGEMENT_WORK_DEPT_NAME;
  final int MANAGEMENT_WORK_DEPT_LEVEL;
  final String MANAGEMENT_OFFICE_CODE;
  final String MANAGEMENT_OFFICE_NAME;
  final String MANAGEMENT_OFFICE_SHORT_NAME;
  final String REPRESENT_POS_CODE;
  final String REPRESENT_POS_NAME;
  final String REPRESENT_POS_LEVEL;
  final String REPRESENT_POS_LEVEL_NAME;
  final String REPRESENT_DEPT_CODE;
  final String REPRESENT_DEPT_NAME;
  final int REPRESENT_DEPT_LEVEL;
  final String REPRESENT_UNDER_DEPT_CODE;
  final String REPRESENT_UNDER_DEPT_NAME;
  final int REPRESENT_UNDER_DEPT_LEVEL;
  final String REPRESENT_WORK_DEPT_CODE;
  final String REPRESENT_WORK_DEPT_NAME;
  final int REPRESENT_WORK_DEPT_LEVEL;
  final String REPRESENT_OFFICE_CODE;
  final String REPRESENT_OFFICE_NAME;
  final String REPRESENT_OFFICE_SHORT_NAME;
  final int STATUS;
  final String REMARK;
  final int CONTRIBUTOR_ID;
  final int IS_ACTIVE;

  ItemsProveStaff({
    this.STAFF_ID,
    this.PROVE_ID,
    this.STAFF_REF_ID,
    this.TITLE_ID,
    this.STAFF_CODE,
    this.ID_CARD,
    this.STAFF_TYPE,
    this.TITLE_NAME_TH,
    this.TITLE_NAME_EN,
    this.TITLE_SHORT_NAME_TH,
    this.TITLE_SHORT_NAME_EN,
    this.FIRST_NAME,
    this.LAST_NAME,
    this.AGE,
    this.OPERATION_POS_CODE,
    this.OPREATION_POS_NAME,
    this.OPREATION_POS_LEVEL,
    this.OPERATION_POS_LEVEL_NAME,
    this.OPERATION_DEPT_CODE,
    this.OPERATION_DEPT_NAME,
    this.OPERATION_DEPT_LEVEL,
    this.OPERATION_UNDER_DEPT_CODE,
    this.OPERATION_UNDER_DEPT_NAME,
    this.OPERATION_UNDER_DEPT_LEVEL,
    this.OPERATION_WORK_DEPT_CODE,
    this.OPERATION_WORK_DEPT_NAME,
    this.OPERATION_WORK_DEPT_LEVEL,
    this.OPERATION_OFFICE_CODE,
    this.OPERATION_OFFICE_NAME,
    this.OPERATION_OFFICE_SHORT_NAME,
    this.MANAGEMENT_POS_CODE,
    this.MANAGEMENT_POS_NAME,
    this.MANAGEMENT_POS_LEVEL,
    this.MANAGEMENT_POS_LEVEL_NAME,
    this.MANAGEMENT_DEPT_CODE,
    this.MANAGEMENT_DEPT_NAME,
    this.MANAGEMENT_DEPT_LEVEL,
    this.MANAGEMENT_UNDER_DEPT_CODE,
    this.MANAGEMENT_UNDER_DEPT_NAME,
    this.MANAGEMENT_UNDER_DEPT_LEVEL,
    this.MANAGEMENT_WORK_DEPT_CODE,
    this.MANAGEMENT_WORK_DEPT_NAME,
    this.MANAGEMENT_WORK_DEPT_LEVEL,
    this.MANAGEMENT_OFFICE_CODE,
    this.MANAGEMENT_OFFICE_NAME,
    this.MANAGEMENT_OFFICE_SHORT_NAME,
    this.REPRESENT_POS_CODE,
    this.REPRESENT_POS_NAME,
    this.REPRESENT_POS_LEVEL,
    this.REPRESENT_POS_LEVEL_NAME,
    this.REPRESENT_DEPT_CODE,
    this.REPRESENT_DEPT_NAME,
    this.REPRESENT_DEPT_LEVEL,
    this.REPRESENT_UNDER_DEPT_CODE,
    this.REPRESENT_UNDER_DEPT_NAME,
    this.REPRESENT_UNDER_DEPT_LEVEL,
    this.REPRESENT_WORK_DEPT_CODE,
    this.REPRESENT_WORK_DEPT_NAME,
    this.REPRESENT_WORK_DEPT_LEVEL,
    this.REPRESENT_OFFICE_CODE,
    this.REPRESENT_OFFICE_NAME,
    this.REPRESENT_OFFICE_SHORT_NAME,
    this.STATUS,
    this.REMARK,
    this.CONTRIBUTOR_ID,
    this.IS_ACTIVE,
  });

  factory ItemsProveStaff.fromJson(Map<String, dynamic> json) {
    return ItemsProveStaff(
      STAFF_ID: json['STAFF_ID'],
      PROVE_ID: json['PROVE_ID'],
      STAFF_REF_ID: json['STAFF_REF_ID'],
      TITLE_ID: json['TITLE_ID'],
      STAFF_CODE: json['STAFF_CODE'],
      ID_CARD: json['ID_CARD'],
      STAFF_TYPE: json['STAFF_TYPE'],
      TITLE_NAME_TH: json['TITLE_NAME_TH'],
      TITLE_NAME_EN: json['TITLE_NAME_EN'],
      TITLE_SHORT_NAME_TH: json['TITLE_SHORT_NAME_TH'],
      TITLE_SHORT_NAME_EN: json['TITLE_SHORT_NAME_EN'],
      FIRST_NAME: json['FIRST_NAME'],
      LAST_NAME: json['LAST_NAME'],
      AGE: json['AGE'],
      OPERATION_POS_CODE: json['OPERATION_POS_CODE'],
      OPREATION_POS_NAME: json['OPREATION_POS_NAME'],
      OPREATION_POS_LEVEL: json['OPREATION_POS_LEVEL'],
      OPERATION_POS_LEVEL_NAME: json['OPERATION_POS_LEVEL_NAME'],
      OPERATION_DEPT_CODE: json['OPERATION_DEPT_CODE'],
      OPERATION_DEPT_NAME: json['OPERATION_DEPT_NAME'],
      OPERATION_DEPT_LEVEL: json['OPERATION_DEPT_LEVEL'],
      OPERATION_UNDER_DEPT_CODE: json['OPERATION_UNDER_DEPT_CODE'],
      OPERATION_UNDER_DEPT_NAME: json['OPERATION_UNDER_DEPT_NAME'],
      OPERATION_UNDER_DEPT_LEVEL: json['OPERATION_UNDER_DEPT_LEVEL'],
      OPERATION_WORK_DEPT_CODE: json['OPERATION_WORK_DEPT_CODE'],
      OPERATION_WORK_DEPT_NAME: json['OPERATION_WORK_DEPT_NAME'],
      OPERATION_WORK_DEPT_LEVEL: json['OPERATION_WORK_DEPT_LEVEL'],
      OPERATION_OFFICE_CODE: json['OPERATION_OFFICE_CODE'],
      OPERATION_OFFICE_NAME: json['OPERATION_OFFICE_NAME'],
      OPERATION_OFFICE_SHORT_NAME: json['OPERATION_OFFICE_SHORT_NAME'],
      MANAGEMENT_POS_CODE: json['MANAGEMENT_POS_CODE'],
      MANAGEMENT_POS_NAME: json['MANAGEMENT_POS_NAME'],
      MANAGEMENT_POS_LEVEL: json['MANAGEMENT_POS_LEVEL'],
      MANAGEMENT_POS_LEVEL_NAME: json['MANAGEMENT_POS_LEVEL_NAME'],
      MANAGEMENT_DEPT_CODE: json['MANAGEMENT_DEPT_CODE'],
      MANAGEMENT_DEPT_NAME: json['MANAGEMENT_DEPT_NAME'],
      MANAGEMENT_DEPT_LEVEL: json['MANAGEMENT_DEPT_LEVEL'],
      MANAGEMENT_UNDER_DEPT_CODE: json['MANAGEMENT_UNDER_DEPT_CODE'],
      MANAGEMENT_UNDER_DEPT_NAME: json['MANAGEMENT_UNDER_DEPT_NAME'],
      MANAGEMENT_UNDER_DEPT_LEVEL: json['MANAGEMENT_UNDER_DEPT_LEVEL'],
      MANAGEMENT_WORK_DEPT_CODE: json['MANAGEMENT_WORK_DEPT_CODE'],
      MANAGEMENT_WORK_DEPT_NAME: json['MANAGEMENT_WORK_DEPT_NAME'],
      MANAGEMENT_WORK_DEPT_LEVEL: json['MANAGEMENT_WORK_DEPT_LEVEL'],
      MANAGEMENT_OFFICE_CODE: json['MANAGEMENT_OFFICE_CODE'],
      MANAGEMENT_OFFICE_NAME: json['MANAGEMENT_OFFICE_NAME'],
      MANAGEMENT_OFFICE_SHORT_NAME: json['MANAGEMENT_OFFICE_SHORT_NAME'],
      REPRESENT_POS_CODE: json['REPRESENT_POS_CODE'],
      REPRESENT_POS_NAME: json['REPRESENT_POS_NAME'],
      REPRESENT_POS_LEVEL: json['REPRESENT_POS_LEVEL'],
      REPRESENT_POS_LEVEL_NAME: json['REPRESENT_POS_LEVEL_NAME'],
      REPRESENT_DEPT_CODE: json['REPRESENT_DEPT_CODE'],
      REPRESENT_DEPT_NAME: json['REPRESENT_DEPT_NAME'],
      REPRESENT_DEPT_LEVEL: json['REPRESENT_DEPT_LEVEL'],
      REPRESENT_UNDER_DEPT_CODE: json['REPRESENT_UNDER_DEPT_CODE'],
      REPRESENT_UNDER_DEPT_NAME: json['REPRESENT_UNDER_DEPT_NAME'],
      REPRESENT_UNDER_DEPT_LEVEL: json['REPRESENT_UNDER_DEPT_LEVEL'],
      REPRESENT_WORK_DEPT_CODE: json['REPRESENT_WORK_DEPT_CODE'],
      REPRESENT_WORK_DEPT_NAME: json['REPRESENT_WORK_DEPT_NAME'],
      REPRESENT_WORK_DEPT_LEVEL: json['REPRESENT_WORK_DEPT_LEVEL'],
      REPRESENT_OFFICE_CODE: json['REPRESENT_OFFICE_CODE'],
      REPRESENT_OFFICE_NAME: json['REPRESENT_OFFICE_NAME'],
      REPRESENT_OFFICE_SHORT_NAME: json['REPRESENT_OFFICE_SHORT_NAME'],
      STATUS: json['STATUS'],
      REMARK: json['REMARK'],
      CONTRIBUTOR_ID: json['CONTRIBUTOR_ID'],
      IS_ACTIVE: json['IS_ACTIVE'],
    );
  }
}